name: Release

on:
  push:
    branches:
      - main
      - next

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
    name: Release
    runs-on: ubuntu-latest
    outputs:
      published: ${{ steps.printoutputs.outputs.published }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.6.3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - run: pnpm install --frozen-lockfile

      - name: Package
        run: pnpm package

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Print Changesets Outputs
        run: echo "${{ toJson(steps.changesets.outputs) }}"

      - id: printoutputs
        run: echo "published=${{ steps.changesets.outputs.published }}" >> "$GITHUB_OUTPUT"

      - name: Build
        if: ${{ steps.changesets.outputs.published == 'true' }}
        env:
          BASE_PATH: "/${{ github.event.repository.name }}"
        run: pnpm build

      - name: Upload Artifacts
        if: ${{ steps.changesets.outputs.published == 'true' }}
        uses: actions/upload-pages-artifact@v2
        with:
          path: "apps/website/build/"

  deploy:
    if: ${{ needs.release.outputs.published == 'true' }}
    name: Deploy
    needs: release
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2
